### ISSUE TITLE
prepare for pitch presentation

### ISSUE THREAD

**Issue by meghanakillada** [web103-group23/TripTrail#7]
[Pitch Guide](https://courses.codepath.org/courses/web103/pages/guide_writing_a_pitch)

**Maggie:**

- Intro the app and your team!
- Why did you team choose the topic?
- Who is your app for?
- Show off your wireframes!

**Arys:**

"Now, let's talk about our Minimum Viable Product (MVP) features:

Trip Creation and Management: Start new trips, invite friends, and manage trip details.
Activity Logging: Keep a detailed log of transports, places, activities, and dining experiences.
Expense Management: Input expenses in real-time, assign payees, and automatically calculate splits at the end.
Estimated Travel Times: Utilize APIs to show users the estimated time of travel between locations.
Document Storage: Upload and access essential travel documents securely.
Booking Redirection: Provide links to booking websites and track user selections for convenience.
For our tech stack, we're using PERN:

PostgreSQL for our relational database.
Express.js and Node.js for the backend server.
React for the frontend user interface.
Specific libraries and APIs include:

Google Maps API: For mapping, location data, and estimated travel times.
OAuth: For secure user authentication.
AWS S3 or Firebase Storage: For storing user-uploaded documents.
Stripe API: Potentially for handling any in-app payments or premium features.
One challenge we're facing is the best method to integrate with external booking websites. We're considering affiliate programs or APIs that allow seamless redirection while tracking user choices.

We'd love to get your feedback on this aspect:

Has anyone worked with booking integrations before?
Are there recommended practices for redirecting users without disrupting their experience?
Any suggestions on handling the tracking of selections ethically and transparently?

**Comment by arysaikyn** [comment]
I'll be the third Assignee
